runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/pyrasite-app/index.html
  upload: dist/pyrasite-app/index.html
- url: /
  static_dir: dist/pyrasite-app


# runtime: python27
# api_version: 1
# threadsafe: true
# handlers:
# - url: /
#   static_files: pyrasite-app/dist/pyrasite-app/index.html
#   upload: pyrasite-app/dist/pyrasite-app/index.html
# - url: /
#   static_dir: dist
